app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::controller('books', 'JSONtestController');


// Route::post('/getmsg','ContactMessagesController@postContactMessage');


Route::get('/testimonal-created',[
    'uses'=>'TestimonalsController@TestimonalCreated',
    'as'=>'testimonal.created'

  ]);

Route::get('/signup', [
        'uses' => 'AuthController@getSignUpPage',
        'as' => 'signup'
    ]);
    Route::post('/signup', [
        'uses' => 'AuthController@postSignUp',
        'as' => 'signup'
    ]);
    Route::get('/login', [
        'uses' => 'AuthController@getSignInPage',
        'as' => 'login'
    ]);
    Route::post('/login', [
        'uses' => 'AuthController@postSignIn',
        'as' => 'login'
    ]);
    
    Route::get('/logout', [
        'uses' => 'AuthController@getLogout',
        'as' => 'logout'
    ]);

// Route::get('/password/reset',[
//    'uses' => 'AuthController@getResetPassword',
//     'as' => 'resetpassword'

//   ]
   
// );

// Password Reset Routes
Route::get('password/reset/{token?}', 'PasswordController@showResetForm');
Route::post('password/email', 'PasswordController@sendResetLinkEmail');
route::post('password/reset', 'PasswordController@reset');



 Route::get('/', [
    'uses'=> 'HomeController@getHome',
    'as' => 'home'
    ]);


 Route::get('/galleries', [
    'uses'=> 'GalleryController@getGalleries',
    'as' => 'galleries'
    ]);


 Route::get('/galleries/{slug}', [
    'uses'=> 'GalleryController@getGallery',
    'as' => 'gallery'
    ]);


 Route::get('/sessions', [
    'uses'=> 'SessionsController@getSessions',
    'as' => 'sessions'
    ]);


 Route::get('/testimonals', [
    'uses'=> 'TestimonalsController@getTestimonals',
    'as' => 'testimonals'
    ]);

// Route::resource('testimonals', 'TestimonalsController');






Route::get('/gotemail/{author_email}/{author_name}',[
    'uses'=>'TestimonalsController@getMailCallback',
    'as'=> 'mail_callback'
  ]);

 Route::get('/about-me', [
    'uses'=> 'AboutMeController@getAboutMe',
    'as' => 'about'
    ]);

 Route::get('/contact', [
    'uses'=> 'ContactMessagesController@index',
    'as' => 'contact'
    ]);


 Route::post('/contact', [
    'uses'=> 'ContactMessagesController@postContactMessage',
    'as' => 'contact.store'
    ]); 

 Route::get('/got-sender-email/{sender_email}/{sender_name}',[
    'uses'=>'ContactMessagesController@getMailCallback',
    'as'=> 'sender_mail_callback'
  ]);


Route::get('/photography-blog',[
    'uses' => 'BlogController@getArchive',
    'as'=>'blog.index'
  ]);


Route::get('photography-blog/{slug}',
  [
  'uses'=> 'BlogController@getSingle',
  'as'=>'blog.single'

  ])->where('slug', '[\w\d\-\_]+');


Route::group([
       
          'middleware' => 'roles',
      'roles'=>['Client']
        ]
        , function () {



Route::get('/create-testimonal',[
    'uses'=> 'TestimonalsController@getTestimonalsForm',
    'as' =>  'testimonal.create'
  ]);

Route::post('/create-testimonal',[
    'uses'=> 'TestimonalsController@postTestimonal',
    'as' =>  'testimonal.store'
  ]);



});

Route::get('posts/autocomplete',
 ['uses'=>'BlogController@autocomplete', 
 'as'=>'blog.autocomplete']);


Route::group([
       
          'middleware' => 'roles',
      'roles'=>['Admin']
        ]
        , function () {


Route::get('newsletter/{id}/delete',
 [
  'uses' => 'ContactMessagesController@getDeleteNewsletter',
  'as'=> 'newsletter_delete']);



});




Route::post('/comment',[
'uses'=>'BlogController@createComment',
'as'=>'createComment',
  'middleware' => 'roles',
      'roles'=>['User','Admin']]);




   
  Route::group([
			   'prefix'=> '/admin',
          'middleware' => 'roles',
      'roles'=>['Admin']
				]
        , function () {


Route::get('/', [
		'uses'=>'AdminController@index',
		'as'=> 'admin.index'
	]);

Route::get('users',[
      'uses'=> 'AdminController@getUsers',
      'as'=> 'admin.users'
  ]);


Route::post('users',[
      'uses'=> 'AdminController@postAdminAssignRoles',
      'as'=> 'admin.assign'
  ]);

Route::resource('home', 'HomeController');


Route::get('home/{id}/delete',[
        'uses' => 'HomeController@getDeleteHomeContent',
        'as'=> 'admin.home.delete'
          ]);

Route::resource('home-slideshow', 'HomeSlideshowController');

Route::get('home-slideshow/{id}/delete',[
        'uses' => 'HomeSlideshowController@getDeleteSlideshowContent',
        'as'=> 'admin.home-slideshow.delete'
          ]);

Route::resource('gallery', 'GalleryController');

Route::get('gallery/{id}/delete',
 [
  'uses' => 'GalleryController@getDeleteGalleryContent',
  'as'=> 'admin.gallery.delete']);

Route::post('image/do-upload', 'GalleryController@doImageUpload');


Route::get('images/{id}/delete',
 [
  'uses' => 'GalleryController@getDeleteImagesContent',
  'as'=> 'admin.images.delete']);

Route::get('gallery/delete/{id}', 'GalleryController@getDeleteGallery');

Route::resource('contact', 'ContactContentController');

Route::get('contact/{id}/delete',
 [
  'uses' => 'ContactContentController@getDeleteContactContent',
  'as'=> 'admin.contact.delete']);

Route::get('contact-message/{id}/delete',
 [
  'uses' => 'ContactMessagesController@getDeleteContactMessage',
  'as'=> 'admin.contact-message.delete']);

Route::resource('sessions', 'SessionsController');

Route::get('sessions/{id}/delete',
 [
  'uses' => 'SessionsController@getDeleteVideoSession',
  'as'=> 'admin.session.delete']);

Route::resource('about-me', 'AboutMeController');


Route::resource('testimonals', 'TestimonalsController');

Route::get('testimonal/{id}/delete',
 [
  'uses' => 'TestimonalsController@getDeleteTestimonal',
  'as'=> 'admin.testimonal.delete']);


Route::resource('newsletter', 'NewsletterController');

Route::get('newsletter/{id}/delete',
 [
  'uses' => 'NewsletterController@getDeleteNewsletter',
  'as'=> 'admin.newsletter.delete']);

Route::resource('authors', 'AuthorsController');

Route::get('authors/{id}/delete',
 [
  'uses' => 'AuthorsController@getDeleteAuthor',
  'as'=> 'admin.authors.delete']);


// Route::resource('blog', 'BlogController');


Route::resource('posts', 'PostController');

Route::resource('categories', 'CategoryController', ['except'=> ['create']]);


Route::post('post-image/do-upload', 'PostController@doPostImageUpload');


Route::get('posts/{id}/delete',
 [
  'uses' => 'PostController@getDeletePost',
  'as'=> 'admin.posts.delete']);


Route::resource('tags', 'TagController', ['except' => ['create']]);

Route::get('tags/{id}/delete',
 [
  'uses' => 'TagController@getDeleteTag',
  'as'=> 'admin.tags.delete']);

Route::resource('comments', 'PostCommentsAdminController');



});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function posts()
    {
    	return $this->belongsToMany('App\Post');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Tag;

use Illuminate\Support\Facades\Session;


class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all(); 
        return view('admin.tags.index', compact('tags'));
    }

  

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [

            'name'=> 'required|max:255'

            ]);

        $tag = new Tag;
        $tag->name = $request->name;
        $tag->save();

        Session::flash('flash_message', 'Tag has been saved!');
        return redirect()->route('admin.tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tag = Tag::find($id);
        return view('admin.tags.show', compact('tag'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::find($id);
        return view('admin.tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag = Tag::find($id);
        $this->validate($request,[
            'name'=>'required|max:255'
            ]);
        $tag->name = $request->name;
        $tag->save();

      Session::flash('flash_message', 'Tag has been updated!');
        return redirect()->route('admin.tags.show',$tag->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function getDeleteTag($id)
    {
        $tag = Tag::find($id);
        $tag->posts()->detach();
        $tag->delete();

        Session::flash('flash_message', 'Tag has been deleted!');
        return redirect()->route('admin.tags.index');
    }
}

resources/views/admin/tags/edit.blade.php
@extends('layouts.admin')
@section('title')
Beata Nykiel Photography - Edit {{ $tag->name }} Tag
@endsection

@section('content')

<div class="row">
	<div class="col-md-8">



	{{ Form::model($tag, ['route'=>['admin.tags.update', $tag->id], 'method'=>'PUT']) }}
		{{ Form::label('name', 'Name:')}}
		{{ Form::text('name', null, ['class'=>'form-control']) }}
		

		{{ Form::submit('Save Changes',['class'=>'btn btn-primary']) }}
		
	{{ Form::close() }}
	</div>
</div>

@endsection

resources/views/admin/tags/index.blade.php
@extends('layouts.admin')

@section('title')
Beata Nykiel Photography - All Tags
@endsection

@section('content')

<div class="row">
	<div class="col-md-8">
	@include('layouts.partials.session-error')
	<h1>Tags</h1>
	<table class="table">
		<thead>
			<tr>
			<th>#</th>
			<th>Name</th>
			</tr>
		</thead>
		<tbody>
		@foreach($tags as $tag)
			<tr>
				<th>{{ $tag->id }}</th>
				<td><a href="{{ route('admin.tags.show', $tag->id) }}">{{ $tag->name }}</a></td>
			</tr>
		@endforeach
		</tbody>
	</table>
	</div>
	<div class="col-md-3">
		<div class="well">
		<h3>Create New Tag</h3>
			{!! Form::open(['route'=> 'admin.tags.store', 'method'=> 'POST']) !!}
			{{ Form::label('name', 'Name:') }}
			{{ Form::text('name', null, ['class' => 'form-control']) }}
			{{ Form::submit('Create New Tag', ['class'=>'btn btn-primary btn-block']) }}
			{!! Form::close() !!}
		</div>
	</div>
</div>


@endsection

resources/views/admin/tags/show.blade.php
@extends('layouts.admin')
@section('title')
Beata Nykiel Photography - {{ $tag->name }}
@endsection

@section('content')
	<div class="row">
		<div class="col-md-8">
		@include('layouts.partials.session-error')
			<h1>{{ $tag->name }} Tag &nbsp<small class="text-info">

@if (count($tag->posts) === 1)
  
   {{ $tag->posts()->count() }} Post

@elseif (count($tag->posts) > 1)
   	{{ $tag->posts()->count() }} Posts
@else
    I don't have any Posts!
@endif


		
		
			 </small></h1>
		</div>
		<div class="col-md-2">
			<a href="{{ route('admin.tags.edit', $tag->id) }}" class="btn btn-primary pull-right btn-block">Edit</a>
		</div>
			<div class="col-md-2">
			<a href="{{ route('admin.tags.delete', $tag->id) }}" class="btn btn-danger pull-right btn-block">Delete</a>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
		<table class="table">
			<thead>
				<tr>
					<th>#</th>
					<th>Title</th>
					<th>Tags</th>
					<th></th>
				</tr>
				<tbody>
					@foreach($tag->posts as $post)
					<tr>
						<th>{{ $post->id }}</th>
						<td>{{ $post->title }}</td>
						<td>
							@foreach($post->tags as $tag)
									<span class="label label-default">{{ $tag->name }}</span>
							@endforeach
						</td>
						<td><a href="{{ route('admin.posts.show', $post->id) }}"	class="btn btn-default btn-small">View</a></td>
					</tr>
					@endforeach
				</tbody>
			</thead>
		</table>
		</div>
	</div>
@endsection